# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'X:\dark_winter_plastic\DarkWinter\Python\framework_2-1-0\packages\mca-mya\mca\mya\tools\cineshoteditor\ui\cine_shot_editor_ui_sub.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(227, 142)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(66, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.shot_number_lineEdit = QtWidgets.QLineEdit(Form)
        self.shot_number_lineEdit.setObjectName("shot_number_lineEdit")
        self.horizontalLayout_2.addWidget(self.shot_number_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMaximumSize(QtCore.QSize(66, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.camera_comboBox = QtWidgets.QComboBox(Form)
        self.camera_comboBox.setObjectName("camera_comboBox")
        self.horizontalLayout_3.addWidget(self.camera_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.start_frame_lineEdit = QtWidgets.QLineEdit(Form)
        self.start_frame_lineEdit.setObjectName("start_frame_lineEdit")
        self.horizontalLayout.addWidget(self.start_frame_lineEdit)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.end_frame_lineEdit = QtWidgets.QLineEdit(Form)
        self.end_frame_lineEdit.setObjectName("end_frame_lineEdit")
        self.horizontalLayout.addWidget(self.end_frame_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Shot Number:"))
        self.label_2.setText(_translate("Form", "Camera:"))
        self.label_3.setText(_translate("Form", "Start:"))
        self.label_4.setText(_translate("Form", "End:"))
        self.pushButton.setText(_translate("Form", "Remove Shot"))
