#! /usr/bin/env python
# -*- coding: utf-8 -*-

"""
Module that contains the mca decorators at a base python level
"""

# mca python imports

# software specific imports

# mca python imports


# Environment Variables Names


MCA_PROJECT_PATH = 'MCA_PROJECT_PATH'
MCA_PROJECT_ROOT = 'MCA_PROJECT_ROOT'
MCA_FRAMEWORK_PATH = 'MCA_FRAMEWORK_PATH'
MCA_PACKAGES_PATH = 'MCA_PACKAGES_PATH'
MCA_COMMON_PATH = 'MCA_COMMON_PATH'
MCA_DEPEND_PATH = 'MCA_DEPEND_PATH'
MCA_MAYA_PATH = 'MCA_MAYA_PATH'
MCA_MOBU_PATH = 'MCA_MOBU_PATH'
MCA_UNREAL_PATH = 'MCA_UNREAL_PATH'
MCA_RESOURCES_PATH = 'MCA_RESOURCES_PATH'
MCA_ICONS_PATH = 'MCA_ICONS_PATH'
MCA_IMAGES_PATH = 'MCA_IMAGES_PATH'
MCA_STYLES_PATH = 'MCA_STYLES_PATH'
MCA_FONTS_PATH = 'MCA_FONTS_PATH'
MCA_COMMON_STARTUP = 'MCA_COMMON_STARTUP'
MCA_CHARACTERS_PATHS = 'MCA_CHARACTERS_PATHS'
MCA_COMMON_FOLDER = 'MCA_COMMON_FOLDER'
MCA_COMMON_TOOLS = 'MCA_COMMON_TOOLS'
MCA_PROJECT_NAME = 'MCA_PROJECT_NAME'


MCA_COMMON_TOP_ROOT = 'MCA_COMMON_BASE_PATH'
MCA_CONFIGS_PATH = 'MCA_COMMON_CONFIGS_PATH'

PLASTIC_ROOT = 'MCA_PLASTIC_ROOT'
PLASTIC_DEV_ROOT = 'MCA_PLASTIC_DEV_ROOT'

MOD_PKG_NAME = 'mca_package.config'
PKG_NAME = 'mca_package.yaml'
START_CONFIG = 'mca_python.config'
PROJECT_CONFIG_NAME = 'mca_python_package.config'
PREF_FOLDER_NAME = 'mca_preferences'
PROJECT_PREFS_FILE = 'mca_project.prefs'
MAYA = 'maya'
MOBU = 'moBu'
UNREAL = 'unreal'
STANDALONE = 'standalone'

