t9717456075002:
  country: 'USA'
  email: 'ncomes@counterplay.co'
  full_name: 'Nathan Comes'
  mat_username: 'ncomes'
  location: 'Texas'
  team: 'Rigging Tech Art'
  title: 'Lead Character Technical Artist'
t2218016846549089:
  country: 'USA'
  email: 'irichter@counterplay.co'
  full_name: 'Isabelle Richter'
  mat_username: 'irichter'
  location: 'New York'
  team: 'Rigging Tech Art'
  title: 'Junior Character Technical Artist'
t8460080995890348:
  country: 'USA'
  email: 'irichter@counterplay.co'
  full_name: 'Isabelle Richter'
  mat_username: 'irichter'
  location: 'New York'
  team: 'Rigging Tech Art'
  title: 'Junior Character Technical Artist'
t1105875678999:
  country: 'USA'
  email: 'fschorsch@counterplay.co'
  full_name: 'Frank Schorsch'
  mat_username: 'fschorsch'
  location: 'Washington'
  team: 'Rigging Tech Art'
  title: 'Senior Character Technical Artist'
t130532133651:
  country: 'USA'
  email: 'charlie@counterplay.co'
  full_name: 'Charlie Tong'
  mat_username: 'charlie'
  location: 'California'
  team: 'Animation'
  title: 'Senior Animator'
t8775608007859553:
  country: 'USA'
  email: 'sroberts@counterplay.co'
  full_name: 'Spencer Roberts'
  mat_username: 'sroberts'
  location: 'Arizona'
  team: 'Animation'
  title: 'Lead Narrative Animator'
t1943521354550:
  country: 'France'
  email: 'jonathan@counterplay.co'
  full_name: 'Jonathan Colin'
  mat_username: 'jonathan'
  location: 'Nantes'
  team: 'Animation'
  title: 'Lead Animator'
t350975874251734:
  country: 'France'
  email: 'hsena@counterplay.co'
  full_name: 'Hugo Sena'
  mat_username: 'hsena'
  location: 'Reunion island'
  team: 'Character Art'
  title: 'Senior Character Artist'
t8140803222053912:
  country: 'France'
  email: 'alexandre@counterplay.co'
  full_name: 'Alexandre Fiolka'
  mat_username: 'alexandre'
  location: 'Farbus'
  team: 'Character Art'
  title: 'Lead Character Artist'
t7928586207201102:
  country: 'USA'
  email: 'ksawosik@counterplay.co'
  full_name: 'Katie Sawosik'
  mat_username: 'ksawosik'
  location: 'California'
  team: 'Animation'
  title: 'Junior Narrative Animator'
t63629491579:
  country: 'USA'
  email: 'christiansherden@counterplay.co'
  full_name: 'Christian Newmark'
  mat_username: 'christiansherden'
  location: 'California'
  team: 'Cinematics'
  title: 'Cinematics Director'
t354977717358732:
  country: 'USA'
  email: 'avidal@counterplay.co'
  full_name: 'Aldo Vidal'
  mat_username: 'avidal'
  location: 'New Hampshire'
  team: 'Character Art'
  title: 'Senior Character Artist'
t5863875259:
  country: 'Sweden'
  email: 'malfredsson@counterplay.co'
  full_name: 'Moa Alfredsson'
  mat_username: 'malfredsson'
  location: 'Stockholm'
  team: 'Character Art'
  title: 'Senior Character Artist'
t145241733527248355:
  country: 'Serbia'
  email: 'pavle@counterplay.co'
  full_name: 'Pavle Plamenac'
  mat_username: 'pavle'
  location: 'Belgrade'
  team: 'Character Art'
  title: 'Junior Character Artist'
t5614171103701665:
  country: 'USA'
  email: 'ncomes@counterplay.co'
  full_name: 'Nathan Comes'
  mat_username: 'ncomes'
  location: 'Texas'
  team: 'Rigging Tech Art'
  title: 'Lead Character Technical Artist'
t171348499962728051905051:
  country: 'Canada'
  email: 'richardboisvert@counterplay.co'
  full_name: 'Richard Boisvert'
  mat_username: 'richardboisvert'
  location: 'Alberta'
  team: 'Cinematics'
  title: 'Senior Cinematic Designer'
t2190158465058:
  country: 'USA'
  email: 'ebarry@counterplay.co'
  full_name: 'Em Barry'
  mat_username: 'ebarry'
  location: 'Indianapolis'
  team: 'Rigging Tech Art'
  title: 'Junior Character Technical Artist'
t57877998656:
  country: 'New Zealand'
  email: 'cjohnston@counterplay.co'
  full_name: 'Craig Johnston'
  mat_username: 'craig'
  location: 'New Plymouth'
  team: 'Animation'
  title: 'Senior Animator'
t46458194264255363:
  country: 'France'
  email: 'rpommier@counterplay.co'
  full_name: 'Romain Pommier'
  mat_username: 'rpommier'
  location: 'Lyon'
  team: 'Character Art'
  title: 'Senior Character Artist'
t1650535632918:
  country: 'USA'
  email: 'jmorey@counterplay.co'
  full_name: 'Jude Morey'
  mat_username: 'jmorey'
  location: 'Indiana'
  team: 'Animator'
  title: 'Gameplay Animator'